CREATE TABLE users(
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(255) UNIQUE,
	login VARCHAR(64) UNIQUE,
	password VARCHAR(64) NOT NULL
);

CREATE TABLE sessions(
	id BIGINT UNSIGNED PRIMARY KEY,
	fk_user INT NOT NULL
);
