CREATE TABLE users(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(255) UNIQUE,
	login VARCHAR(64) UNIQUE,
	password VARCHAR(64) NOT NULL
);

CREATE TABLE sessions(
	token INT UNSIGNED PRIMARY KEY,
	fk_user INT UNSIGNED NOT NULL
);

CREATE TABLE notes(
	id INT UNSIGNED PRIMARY KEY,
	fk_user INT UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL
);
